CREATE DATABASE [Vendors] -- adatbázis létrehozás
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Vendors', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Vendors.mdf' , SIZE = 153600KB , FILEGROWTH = 12%), 
 FILEGROUP [SalesData] 
( NAME = N'Vendors_SalesData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Vendors_SalesData.ndf' , SIZE = 153600KB , FILEGROWTH = 12%)
 LOG ON 
( NAME = N'Vendors_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Vendors_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 COLLATE Hungarian_CI_AS
GO
ALTER DATABASE [Vendors] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Vendors] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Vendors] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Vendors] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Vendors] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Vendors] SET ARITHABORT OFF 
GO
ALTER DATABASE [Vendors] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Vendors] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Vendors] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Vendors] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Vendors] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Vendors] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Vendors] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Vendors] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Vendors] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Vendors] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Vendors] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Vendors] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Vendors] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Vendors] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Vendors] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Vendors] SET  READ_WRITE 
GO
ALTER DATABASE [Vendors] SET RECOVERY FULL 
GO
ALTER DATABASE [Vendors] SET  MULTI_USER 
GO
ALTER DATABASE [Vendors] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Vendors] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Vendors] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Vendors]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Vendors]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Vendors] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO



-- ---------------------------------------------------------------------------------

USE [master]
GO
CREATE LOGIN [VendorAdmin] WITH PASSWORD=N'Pa55w.rd', DEFAULT_DATABASE=[Vendors], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
use [Vendors];
GO
use [master];
GO
USE [Vendors]
GO
CREATE USER [VendorAdmin] FOR LOGIN [VendorAdmin]
GO
USE [Vendors]
GO
ALTER ROLE [db_owner] ADD MEMBER [VendorAdmin]
GO

-- --------------------------------------------------------------------------------

USE [master]
GO
CREATE LOGIN [VendorRO] WITH PASSWORD=N'Pa55w.rd', DEFAULT_DATABASE=[Vendors], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Vendors]
GO
CREATE USER [VendorRO] FOR LOGIN [VendorRO]
GO
USE [Vendors]
GO
ALTER ROLE [db_datareader] ADD MEMBER [VendorRO]
GO

-- --------------------------------------------------------------------------------

--  3., feledat esetén azt gondolom, hogy ha a VendorAdmin user "db_owner" akkor mennie kell az openrowset utasításnak
